# Generated by Django 3.2.3 on 2021-09-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='rock.jpg', upload_to='rock_pics'),
        ),
    ]
