# Generated by Django 3.2.8 on 2021-10-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='transaction_ID',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_ID',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order',
            new_name='order_ID',
        ),
    ]
