# Generated by Django 3.2.8 on 2021-10-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_item_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='itemName',
        ),
    ]
