# Generated by Django 3.2.8 on 2021-10-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_item_orderitem_itemname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='profile',
            new_name='user',
        ),
    ]
