# Generated by Django 3.2.8 on 2021-10-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_profile_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='itemName',
            new_name='itemname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='itemPrice',
            new_name='itemprice',
        ),
    ]
