# Generated by Django 3.2.8 on 2021-10-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20211020_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='itemName',
            new_name='product',
        ),
    ]
